### ISSUE TITLE
Small typo in line 646 of ImageD11.sinograms.properties

### ISSUE THREAD

**Issue by haixing0a** [FABLE-3DXRD/ImageD11#175]
Line 646: sps.motors['omega'] = ds.omega[i]
After I change this line to sps.motors['omega'] = ds.omega, it would work for me.

**Comment by jonwright** [comment]
Thanks! I am expecting it should be ds.omega[row], because I usually have ds.omega as a [nscans, npoints] array.

Have you got something where ds is a 1D array? This code is missing some testcases ...

**Comment by haixing0a** [comment]
I was processing the users' box beam 3DXRD data last week, which would become 1D array. Maybe it can be adapted to this scenario by checking the ds shape?

**Comment by jonwright** [comment]
The bug is in: /data/id11/3dxrd/haixing/user_exp/Box_beam_3DXRD/0_preprocessing.ipynb

You should use ds.import_motors_from_master, or otherwise ds.omega = [ omega_array , ]

I suggest putting your notebooks into a pull request for maintaining and testing in git here. In most cases, we could probably add functions that are not in ipython notebooks that do the things you need. So far, it seems very hard to test and maintain code that is in notebooks - perhaps there is some trick to running them under CI.

The ds.shape has a problem for now when scans are not all the same length. But regardless, the ds.omega should stay dimensioned by scans for the case where someone does 2 scans, on each side of the ADMET, etc. One scan is not a special case.
